name: travel_hour
description: A new Flutter application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 4.2.0+19

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  another_carousel_pro:
    git:
      url: https://github.com/iamnabink/another_carousel_pro
      ref: 6bd1b57
  app_settings: ^5.1.1
  bloc: ^8.1.4
  cached_network_image: ^3.4.0
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.2.1
  cupertino_icons: ^1.0.8
  dots_indicator: ^3.0.0
  dropdown_button2: ^2.3.9
  easy_localization: ^3.0.2
  equatable: ^2.0.5
  firebase_analytics: ^11.2.1
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_in_app_messaging: ^0.8.0+4
  firebase_messaging: ^15.0.4
  firebase_storage: ^12.1.3
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_facebook_auth: ^7.1.0
  flutter_html: ^3.0.0-beta.2
  flutter_icons:
    git:
      url: https://github.com/adarsh-technocrat/flutter-icons
  flutter_inappwebview: ^6.1.3
  flutter_polyline_points: ^2.1.0
  flutter_screenutil: ^5.9.0
  flutter_tts: ^3.8.5
  flutter_web_browser: ^0.17.1
  flutter_web_plugins:
    sdk: flutter
  fluttertoast: ^8.2.8
  focus_detector: ^2.0.1
  geo: ^0.3.0
  geolocator: ^13.0.1
  go_router: ^14.4.1
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.9.0
  google_maps_flutter_web: ^0.5.10
  google_mobile_ads: ^5.1.0
  google_sign_in: ^6.2.1
  html_unescape: ^2.0.0
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  ionicons: ^0.2.2
  just_audio: ^0.9.40
  launch_review: ^3.0.1
  line_icons: ^2.0.3
  md2_tab_indicator:
    git:
      url: https://github.com/westdabestdb/md2_tab_indicator
  mobile_scanner: ^5.2.3
  package_info_plus: ^8.0.2
  permission_handler: ^10.2.0
  pod_player: ^0.2.2
  provider: ^6.1.2
  responsive_builder: ^0.4.3
  share: ^2.0.4
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  simple_ripple_animation: ^0.0.9
  skeleton_text: ^3.0.1
  sliding_up_panel: ^2.0.0+1
  speech_to_text: ^6.6.0
  table_calendar: ^3.1.2
  the_apple_sign_in: ^1.1.1
  translator: ^1.0.0
  uni_links: ^0.5.1
  universal_platform: ^1.1.0
  url_launcher: ^6.3.0
  wakelock: ^0.6.2

dev_dependencies:
  change_app_package_name: ^1.3.0

  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

dependency_overrides:
  uuid: ^4.4.0
  meta: ^1.10.0
  win32: ^5.5.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/geojson/
    - assets/images/
    - assets/images/ia_icons/
    - assets/images/destination/
    - assets/images/markers/
    - assets/flr/
    - assets/translations/
    - assets/data/

  fonts:
    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji-Regular.ttf
    - family: Muli
      fonts:
        # - asset: fonts/Montserrat-Light.ttf
        #   weight: 400
        - asset: assets/fonts/Muli-Regular.ttf
          weight: 500
        - asset: assets/fonts/Muli-Medium.ttf
          weight: 600
        - asset: assets/fonts/Muli-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Muli-Bold.ttf
          weight: 800

    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 900

    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 500
