// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq_XLGUN8g-0gyQtO2GkDzLHvBEioVhwE',
    appId: '1:74569608969:web:15677b7a6cd62ae8126dd8',
    messagingSenderId: '74569608969',
    projectId: 'conectaquindio-80908',
    authDomain: 'conectaquindio-80908.firebaseapp.com',
    storageBucket: 'conectaquindio-80908.appspot.com',
    measurementId: 'G-P99GZ3LF3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYXdVqxOm671zNtK9ntSnFWUlkbw4QcWA',
    appId: '1:74569608969:android:a43b8cec133eb06c126dd8',
    messagingSenderId: '74569608969',
    projectId: 'conectaquindio-80908',
    storageBucket: 'conectaquindio-80908.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5_lFWAHslQTHaV_n58cu-LWqkGo3NbMs',
    appId: '1:74569608969:ios:8fa8091e3dda8a24126dd8',
    messagingSenderId: '74569608969',
    projectId: 'conectaquindio-80908',
    storageBucket: 'conectaquindio-80908.appspot.com',
    androidClientId: '74569608969-clioob16pkigc6ohe38los7taopnp6fq.apps.googleusercontent.com',
    iosClientId: '74569608969-p0j8ue7tq2jtf0svj8a992psjnpi66am.apps.googleusercontent.com',
    iosBundleId: 'com.conectaquindio.app',
  );
}
